### ISSUE TITLE
When I use the cityscapes dataset for training, I encounter an error when loading the model. How to solve this problem?

### ISSUE THREAD

**Issue by a139122679** [jianlong-yuan/SimpleBaseline#4]
2021-12-23 11:41:25,981 Segmentron INFO: train_fine data num 2975
2021-12-23 11:41:26,012 Segmentron INFO: train_fine data num 2975
2021-12-23 11:41:26,017 Segmentron INFO: val_fine data num 500
2021-12-23 11:41:26,763 Segmentron INFO: DSSyncBatchNorm is effective!
Traceback (most recent call last):
  File "tools/train_semi.py", line 284, in <module>
    trainer = Trainer(args)
  File "tools/train_semi.py", line 79, in __init__
    self.model = get_segmentation_model().to(self.device)
  File "/user/lwx1055260/ID2450_SimpleBaseline_for_pytorch/segmentron/models/model_zoo.py", line 27, in get_segmentation_model
    load_model_pretrain(model)
  File "/user/lwx1055260/ID2450_SimpleBaseline_for_pytorch/segmentron/models/model_zoo.py", line 34, in load_model_pretrain
    assert os.path.exists(cfg.TRAIN.PRETRAINED_MODEL_PATH)
AssertionError
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=4 : driver shutting down

**Comment by jianlong-yuan** [comment]
please download the pre-trained model. For more details check https://github.com/jianlong-yuan/SimpleBaseline/blob/main/segmentron/models/backbones/build.py .

**Comment by daeunni** [comment]
@jianlong-yuan  what is `PRETRAINED_MODEL_PATH: "/**/best_model.pth"` ?
